version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: AttendanceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: backend/AttendanceApi/.
    container_name: backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: frontend/AttendanceUI/.
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  migration:
    build:
      dockerfile: backend/AttendanceApi/migrate.Dockerfile
    container_name: migration
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
