// <auto-generated />
using System;
using Backend.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Iphone"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Ipad"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Macbook"
                        });
                });

            modelBuilder.Entity("Backend.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            Name = "Rose"
                        },
                        new
                        {
                            ColorId = 2,
                            Name = "Gold"
                        },
                        new
                        {
                            ColorId = 3,
                            Name = "White"
                        },
                        new
                        {
                            ColorId = 4,
                            Name = "Black"
                        },
                        new
                        {
                            ColorId = 5,
                            Name = "Grey"
                        });
                });

            modelBuilder.Entity("Backend.Models.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "What the hell?",
                            Email = "chien.vh@gmail.com",
                            Name = "Chien Vu",
                            Phone = "986665248"
                        },
                        new
                        {
                            Id = 2,
                            Content = "2nd time for submitting form. thanks",
                            Email = "chien.vh@gmail.com",
                            Name = "Chien Vu Hoang",
                            Phone = "986665248"
                        });
                });

            modelBuilder.Entity("Backend.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModelId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            Name = "6S Rose Gold"
                        },
                        new
                        {
                            ModelId = 2,
                            Name = "6S Gold"
                        },
                        new
                        {
                            ModelId = 3,
                            Name = "6 Gold"
                        },
                        new
                        {
                            ModelId = 4,
                            Name = "6 Grey"
                        },
                        new
                        {
                            ModelId = 5,
                            Name = "6S Rose Plus"
                        },
                        new
                        {
                            ModelId = 6,
                            Name = "6S Gold Plus"
                        },
                        new
                        {
                            ModelId = 7,
                            Name = "6 Gold Plus"
                        },
                        new
                        {
                            ModelId = 8,
                            Name = "6 Grey Plus"
                        },
                        new
                        {
                            ModelId = 9,
                            Name = "5S Gold"
                        },
                        new
                        {
                            ModelId = 10,
                            Name = "5S Black"
                        },
                        new
                        {
                            ModelId = 11,
                            Name = "5S White"
                        },
                        new
                        {
                            ModelId = 12,
                            Name = "5 White"
                        },
                        new
                        {
                            ModelId = 13,
                            Name = "5 Black"
                        },
                        new
                        {
                            ModelId = 14,
                            Name = "Ipad Mini 1"
                        },
                        new
                        {
                            ModelId = 15,
                            Name = "Ipad Mini 2"
                        },
                        new
                        {
                            ModelId = 16,
                            Name = "Ipad Mini 3"
                        },
                        new
                        {
                            ModelId = 17,
                            Name = "Ipad Mini 4"
                        },
                        new
                        {
                            ModelId = 18,
                            Name = "Ipad 2"
                        },
                        new
                        {
                            ModelId = 19,
                            Name = "Ipad 3"
                        },
                        new
                        {
                            ModelId = 20,
                            Name = "Ipad 4"
                        },
                        new
                        {
                            ModelId = 21,
                            Name = "Ipad Air"
                        },
                        new
                        {
                            ModelId = 22,
                            Name = "Macbook Pro"
                        },
                        new
                        {
                            ModelId = 23,
                            Name = "Macbook Pro Retina"
                        });
                });

            modelBuilder.Entity("Backend.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = 2,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description first",
                            Status = 1,
                            Title = "My Testing First",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 3,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 2",
                            Status = 1,
                            Title = "My Testing 2",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 4,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 3",
                            Status = 1,
                            Title = "My Testing 3",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 5,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 4",
                            Status = 1,
                            Title = "My Testing 4",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 6,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 5",
                            Status = 1,
                            Title = "My Testing 5",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 7,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 6",
                            Status = 1,
                            Title = "My Testing 6",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 8,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 7",
                            Status = 1,
                            Title = "My Testing 7",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 9,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 8",
                            Status = 1,
                            Title = "My Testing 8",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 10,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 9",
                            Status = 1,
                            Title = "My Testing 9",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 11,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 10",
                            Status = 1,
                            Title = "My Testing 10",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 12,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 11",
                            Status = 1,
                            Title = "My Testing 11",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 13,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 12",
                            Status = 1,
                            Title = "My Testing 12",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 14,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 13",
                            Status = 1,
                            Title = "My Testing 13",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 15,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 14",
                            Status = 1,
                            Title = "My Testing 14",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 16,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 15",
                            Status = 1,
                            Title = "My Testing 15",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 17,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 16",
                            Status = 1,
                            Title = "My Testing 16",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 18,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 17",
                            Status = 1,
                            Title = "My Testing 17",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 19,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 18",
                            Status = 1,
                            Title = "My Testing 18",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 20,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 19",
                            Status = 1,
                            Title = "My Testing 19",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 21,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 20",
                            Status = 1,
                            Title = "My Testing 20",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 22,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 6 Plus 16Gb Grey.jpg",
                            ShortDescription = "This is the short description 21",
                            Status = 1,
                            Title = "My Testing 21",
                            UserId = 1
                        },
                        new
                        {
                            NewsId = 23,
                            Content = "Content should be here. Will be updated later",
                            CreatedDate = new DateTime(2015, 11, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "iPhone 5S 32GB Silver.jpg",
                            ShortDescription = "This is the short description 22",
                            Status = 1,
                            Title = "My Testing 22",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien Vu",
                            CustomerPhone = "84986665248",
                            OrderDate = new DateTime(2017, 7, 1, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 1",
                            PaymentType = "Cash",
                            Status = "Paid"
                        },
                        new
                        {
                            OrderID = 2,
                            CustomerAddress = "Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@hotmail.com",
                            CustomerName = "Chien Vu Hoang",
                            CustomerPhone = "84986665248",
                            OrderDate = new DateTime(2017, 7, 6, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 2",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 3,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Hoang Hop",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 3",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 4,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Hop Hoang",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 4",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 5,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien VH",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 5",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 6,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 6",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 7,
                            CustomerAddress = "My Dinh, Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien Hoang",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 7",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 8,
                            CustomerAddress = "Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Hop HT",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 26, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 8",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 9,
                            CustomerAddress = "Ha Noi, Viet Nam",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien Vu",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 8, 26, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 9",
                            PaymentType = "Cash",
                            Status = "Processing"
                        },
                        new
                        {
                            OrderID = 10,
                            CustomerAddress = "P806, Nha B2, Khu Do Thi My Dinh 1, My Dinh, Tu Liem, Ha Noi",
                            CustomerEmail = "chien.vh@gmail.com",
                            CustomerName = "Chien Vu",
                            CustomerPhone = "986665248",
                            OrderDate = new DateTime(2017, 9, 2, 18, 30, 0, 0, DateTimeKind.Utc),
                            OrderName = "Order 10",
                            PaymentType = "Cash",
                            Status = "Processing"
                        });
                });

            modelBuilder.Entity("Backend.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            ProductID = 23,
                            Price = 549.0,
                            Quantity = 5
                        },
                        new
                        {
                            OrderID = 1,
                            ProductID = 20,
                            Price = 649.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderID = 1,
                            ProductID = 22,
                            Price = 549.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 2,
                            ProductID = 22,
                            Price = 549.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 3,
                            ProductID = 20,
                            Price = 649.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 4,
                            ProductID = 17,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 5,
                            ProductID = 21,
                            Price = 649.0,
                            Quantity = 5
                        },
                        new
                        {
                            OrderID = 6,
                            ProductID = 22,
                            Price = 549.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 6,
                            ProductID = 20,
                            Price = 649.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 6,
                            ProductID = 23,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 7,
                            ProductID = 19,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 7,
                            ProductID = 21,
                            Price = 649.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 8,
                            ProductID = 17,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 8,
                            ProductID = 20,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 8,
                            ProductID = 22,
                            Price = 549.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 8,
                            ProductID = 14,
                            Price = 649.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 9,
                            ProductID = 23,
                            Price = 549.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 9,
                            ProductID = 20,
                            Price = 649.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 10,
                            ProductID = 7,
                            Price = 649.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 10,
                            ProductID = 15,
                            Price = 549.0,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IsNew")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SellEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SellStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StorageId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ColorId = 1,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 849.0,
                            ProductName = "Iphone 7 Rose 32GB",
                            SellEndDate = new DateTime(2016, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ColorId = 2,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 0,
                            ModelId = 1,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2014, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 549.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            ColorId = 3,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "Ipad1.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 649.0,
                            ProductName = "Ipad Air 4",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 649.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 649.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 549.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            ColorId = 1,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            ColorId = 2,
                            Image = "macbook1.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 20.0,
                            ProductName = "Macbook Pro 2016",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 3,
                            ColorId = 2,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 1,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            ColorId = 2,
                            Image = "macbook2.jpg",
                            IsNew = 0,
                            ModelId = 2,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            ColorId = 2,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 0,
                            ModelId = 2,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 0,
                            ModelId = 2,
                            Price = 649.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1,
                            ColorId = 1,
                            Image = "iPhone 6S 16GB Gold.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 549.0,
                            ProductName = "Iphone 6 Gold 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 1,
                            ColorId = 1,
                            Image = "iPhone 6 128GB.jpg",
                            IsNew = 1,
                            ModelId = 2,
                            Price = 549.0,
                            ProductName = "Iphone 6S Rose 16GB",
                            SellEndDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            SellStartDate = new DateTime(2015, 9, 8, 18, 30, 0, 0, DateTimeKind.Utc),
                            StorageId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "chienvh",
                            Username = "chienvh"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backend.Models.News", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("News")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.OrderDetail", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Backend.Models.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId");

                    b.HasOne("Backend.Models.Model", "Model")
                        .WithMany("Products")
                        .HasForeignKey("ModelId");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Model", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
