import { Component } from '@angular/core';
import { FilterMenu } from '../filter-menu/filter-menu';
import { SessionsTable } from '../sessions-table/sessions-table';

@Component({
  selector: 'app-my-sessions-page',
  imports: [FilterMenu, SessionsTable],
  templateUrl: './my-sessions-page.html',
  styleUrl: './my-sessions-page.css',
})
export class MySessionsPage {
  allSessions = [
    {
      id: 1,
      title: 'Angular Basics',
      date: '2025-06-01',
      startTime: '09:00 AM',
      endTime: '10:30 AM',
      status: 'Scheduled',
    },
    {
      id: 2,
      title: 'RxJS in Depth',
      date: '2025-06-02',
      startTime: '11:00 AM',
      endTime: '12:30 PM',
      status: 'Completed',
    },
    {
      id: 3,
      title: 'NgRx State Management',
      date: '2025-06-03',
      startTime: '02:00 PM',
      endTime: '03:30 PM',
      status: 'Scheduled',
    },
    {
      id: 4,
      title: 'Angular Forms Advanced',
      date: '2025-06-04',
      startTime: '10:00 AM',
      endTime: '11:30 AM',
      status: 'Cancelled',
    },
    {
      id: 5,
      title: 'Routing Deep Dive',
      date: '2025-06-05',
      startTime: '01:00 PM',
      endTime: '02:30 PM',
      status: 'Live',
    },
    {
      id: 6,
      title: 'Change Detection Strategy',
      date: '2025-06-06',
      startTime: '03:00 PM',
      endTime: '04:30 PM',
      status: 'Scheduled',
    },
    {
      id: 7,
      title: 'Testing Angular Apps',
      date: '2025-06-07',
      startTime: '10:00 AM',
      endTime: '11:00 AM',
      status: 'Completed',
    },
    {
      id: 8,
      title: 'Angular Animations',
      date: '2025-06-08',
      startTime: '11:30 AM',
      endTime: '01:00 PM',
      status: 'Scheduled',
    },
    {
      id: 9,
      title: 'Dependency Injection',
      date: '2025-06-09',
      startTime: '02:00 PM',
      endTime: '03:00 PM',
      status: 'Completed',
    },
    {
      id: 10,
      title: 'Standalone Components',
      date: '2025-06-10',
      startTime: '09:30 AM',
      endTime: '10:30 AM',
      status: 'Live',
    },
    {
      id: 11,
      title: 'Module Federation',
      date: '2025-06-11',
      startTime: '10:00 AM',
      endTime: '11:30 AM',
      status: 'Cancelled',
    },
    {
      id: 12,
      title: 'Building Reusable Libraries',
      date: '2025-06-12',
      startTime: '12:00 PM',
      endTime: '01:30 PM',
      status: 'Scheduled',
    },
    {
      id: 13,
      title: 'Unit Testing Deep Dive',
      date: '2025-06-13',
      startTime: '02:00 PM',
      endTime: '03:30 PM',
      status: 'Completed',
    },
    {
      id: 14,
      title: 'Integrating with REST APIs',
      date: '2025-06-14',
      startTime: '10:30 AM',
      endTime: '12:00 PM',
      status: 'Scheduled',
    },
    {
      id: 15,
      title: 'Accessibility in Angular',
      date: '2025-06-15',
      startTime: '01:00 PM',
      endTime: '02:00 PM',
      status: 'Live',
    },
    {
      id: 16,
      title: 'Performance Optimization',
      date: '2025-06-16',
      startTime: '03:00 PM',
      endTime: '04:00 PM',
      status: 'Completed',
    },
    {
      id: 17,
      title: 'Angular Material UI',
      date: '2025-06-17',
      startTime: '10:00 AM',
      endTime: '11:30 AM',
      status: 'Scheduled',
    },
    {
      id: 18,
      title: 'Progressive Web Apps',
      date: '2025-06-18',
      startTime: '11:00 AM',
      endTime: '12:00 PM',
      status: 'Completed',
    },
    {
      id: 19,
      title: 'Multi-language Support',
      date: '2025-06-19',
      startTime: '01:30 PM',
      endTime: '03:00 PM',
      status: 'Scheduled',
    },
    {
      id: 20,
      title: 'Auth with JWT',
      date: '2025-06-20',
      startTime: '02:00 PM',
      endTime: '03:30 PM',
      status: 'Live',
    },
    {
      id: 21,
      title: 'Responsive Design Techniques',
      date: '2025-06-21',
      startTime: '09:00 AM',
      endTime: '10:30 AM',
      status: 'Completed',
    },
    {
      id: 22,
      title: 'Custom Pipes and Directives',
      date: '2025-06-22',
      startTime: '11:00 AM',
      endTime: '12:30 PM',
      status: 'Scheduled',
    },
    {
      id: 23,
      title: 'API Caching Strategies',
      date: '2025-06-23',
      startTime: '01:00 PM',
      endTime: '02:00 PM',
      status: 'Cancelled',
    },
    {
      id: 24,
      title: 'Using Signals in Angular',
      date: '2025-06-24',
      startTime: '03:00 PM',
      endTime: '04:30 PM',
      status: 'Scheduled',
    },
    {
      id: 25,
      title: 'Angular v17 Preview',
      date: '2025-06-25',
      startTime: '10:00 AM',
      endTime: '11:00 AM',
      status: 'Completed',
    },
    {
      id: 26,
      title: 'Working with IndexedDB',
      date: '2025-06-26',
      startTime: '11:30 AM',
      endTime: '01:00 PM',
      status: 'Scheduled',
    },
    {
      id: 27,
      title: 'Offline First Apps',
      date: '2025-06-27',
      startTime: '02:00 PM',
      endTime: '03:00 PM',
      status: 'Live',
    },
    {
      id: 28,
      title: 'Design Systems in Angular',
      date: '2025-06-28',
      startTime: '09:30 AM',
      endTime: '10:30 AM',
      status: 'Cancelled',
    },
    {
      id: 29,
      title: 'Intro to Signals and Reactivity',
      date: '2025-06-29',
      startTime: '10:00 AM',
      endTime: '11:30 AM',
      status: 'Scheduled',
    },
    {
      id: 30,
      title: 'Security in Angular Apps',
      date: '2025-06-30',
      startTime: '12:00 PM',
      endTime: '01:30 PM',
      status: 'Completed',
    },
  ];
}
