version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - common-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
